import logo from '../assets/images/logo.png';
import lg1 from '../assets/images/lg1.png';
import lg2 from '../assets/images/lg2.png';
import lg3 from '../assets/images/lg3.png';
import share from '../assets/images/share.png';
import pro1 from '../assets/images/pro1.png';
import pro2 from '../assets/images/pro2.png';
import pro3 from '../assets/images/pro3.png';
import pro4 from '../assets/images/pro4.png';
export const LG_IMG = [lg1,lg2,lg3,logo,share];
export const PROJECT_IMG = [share,pro1,pro2,pro3,pro4];
